from enum import Enum


class TerrainString(Enum):
    GRASSLAND = "grassland"
    PLAINS = "plains"
    DESERT = "desert"
    TUNDRA = "tundra"
    SNOW = "snow"
    COAST = "coast"
    OCEAN = "ocean"
    LAKE = "lake"


class FeatureString(Enum):
    NONE = "none"
    WOODS = "woods"
    JUNGLE = "jungle"
    MARSH = "marsh"
    FLOODPLAINS = "floodplains"
    OASIS = "oasis"
    CLIFFS = "cliffs"
    REEF = "reef"
    GEOTHERMAL_FISSURE = "geothermal_fissure"
    MOUNTAIN = "mountain_unused"
    VOLCANO = "volcano"
    VOLCANIC_SOIL = "volcanic_soil"
    ICE_CAPS = "ice_caps"


class NaturalWonderString(Enum):
    NONE = "none"
    CLIFFS_OF_DOVER = "cliffs_of_dover"
    CRATER_LAKE = "crater_lake"
    DEAD_SEA = "dead_sea"
    GALAPAGOS = "galapagos"
    GREAT_BARRIER_REEF = "great_barrier_reef"
    MOUNT_EVEREST = "mount_everest"
    MOUNT_KILIMANJARO = "mount_kilimanjaro"
    PANTANAL = "pantanal"
    TORRES_DEL_PAINE = "torres_del_paine"
    TSINGY_DE_BEMARAHA = "tsingy_de_bemaraha"
    ULURU = "uluru"
    YOSEMITE = "yosemite"
    DELICATE_ARCH = "delicate_arch"
    EYE_OF_THE_SAHARA = "eye_of_the_sahara"
    LAKE_RETBA = "lake_retba"
    MATTERHORN = "matterhorn"
    MOUNT_RORAIMA = "mount_roraima"
    UBSUNUR_HOLLOW = "ubsunur_hollow"
    ZHANGYE_DANXIA = "zhangye_danxia"
    CHOCOLATE_HILLS = "chocolate_hills"
    GOBUSTAN = "gobustan"
    IK_KIL = "ik_kil"
    MATO_TIPILA = "mato_tipila"
    MOUNT_VESUVIUS = "mount_vesuvius"
    PAMUKKALE = "pamukkale"
    SAHARA_EL_BEYDA = "sahara_el_beyda"
    BERMUDA_TRIANGLE = "bermuda_triangle"
    FOUNTAIN_OF_YOUTH = "fountain_of_youth"
    PAITITI = "paititi"
    HA_LONG_BAY = "ha_long_bay"
    EYJAFJALLAJOKULL = "eyjafjallajokull"
    GIANTS_CAUSEWAY = "giants_causeway"
    LYSEFJORD = "lysefjord"
    PIOPIOTAHI = "piopiotahi"


class DistrictString(Enum):
    NONE = "none"
    CITY_CENTER = "city_center"
    CAMPUS = "campus"
    THEATER_SQUARE = "theater_square"
    HOLY_SITE = "holy_site"
    ENCAMPMENT = "encampment"
    COMMERCIAL_HUB = "commercial_hub"
    HARBOR = "harbor"
    INDUSTRIAL_ZONE = "industrial_zone"
    PRESERVE = "preserve"
    ENTERTAINMENT_COMPLEX = "entertainment_complex"
    WATER_PARK = "water_park"
    AQUEDUCT = "aqueduct"
    NEIGHBORHOOD = "neighborhood"
    CANAL = "canal"
    DAM = "dam"
    AERODROME = "aerodrome"
    SPACEPORT = "spaceport"
    GOVERNMENT_PLAZA = "government_plaza"
    DIPLOMATIC_QUARTER = "diplomatic_quarter"


class ResourceTypeString(Enum):
    NONE = "none"
    BONUS_RESOURCE = "bonus"
    LUXURY_RESOURCE = "luxury"
    STRATEGIC_RESOURCE = "strategic"
    ARTIFACT = "artifact"


class ResourceString(Enum):
    NONE = "none"

    # Bonus Resources
    BANANAS = "bananas"
    CATTLE = "cattle"
    COPPER = "copper"
    CRABS = "crabs"
    DEER = "deer"
    FISH = "fish"
    MAIZE = "maize"
    RICE = "rice"
    SHEEP = "sheep"
    STONE = "stone"
    WHEAT = "wheat"

    # Luxury Resources
    AMBER = "amber"
    CINNAMON = "cinnamon"
    CITRUS = "citrus"
    CLOVES = "cloves"
    COCOA = "cocoa"
    COFFEE = "coffee"
    COSMETICS = "cosmetics"
    COTTON = "cotton"
    DYES = "dyes"
    DIAMONDS = "diamonds"
    FURS = "furs"
    GYPSUM = "gypsum"
    HONEY = "honey"
    INCENSE = "incense"
    IVORY = "ivory"
    JADE = "jade"
    JEANS = "jeans"
    MARBLE = "marble"
    MERCURY = "mercury"
    OLIVES = "olives"
    PEARLS = "pearls"
    PERFUME = "perfume"
    SALT = "salt"
    SILK = "silk"
    SILVER = "silver"
    SPICES = "spices"
    SUGAR = "sugar"
    TEA = "tea"
    TOBACCO = "tobacco"
    TOYS = "toys"
    TRUFFLES = "truffles"
    TURTLES = "turtles"
    WHALES = "whales"
    WINE = "wine"

    # Strategic Resources
    HORSES = "horses"
    IRON = "iron"
    NITER = "niter"
    COAL = "coal"
    OIL = "oil"
    ALUMINUM = "aluminum"
    URANIUM = "uranium"

    # Artifacts
    ANTIQUITY_SITE = "antiquity_site"
    SHIPWRECK = "shipwreck"


class ImprovementString(Enum):
    NONE = "none"
    FARM = "farm"
    MINE = "mine"
    QUARRY = "quarry"
    PLANTATION = "plantation"
    CAMP = "camp"
    PASTURE = "pasture"
    FISHING_BOATS = "fishing_boats"
    LUMBER_MILL = "lumber_mill"


class YieldTypeString(Enum):
    SCIENCE = "science"
    CULTURE = "culture"
    GOLD = "gold"
    FAITH = "faith"
    PRODUCTION = "production"
    FOOD = "food"
